language: python

python:
  - "3.6"

install:
  - pip install --upgrade awscli
  - pip install yamllint

script:
  - pwd
  - ls -l
  #- aws cloudformation validate-template --template-body file://cloudformation/my-template.yml
  #- yaml-lint cloudformation/my-template.yml

after_success:
  - echo "SUCCCESS"

after_failure:
  - echo "FAILURE"
