language: python

python:
  - "3.6"

install:
  - pip install --upgrade awscli
  - pip install yamllint

script:
  - yamllint cloudformation-bucket.yaml
  - aws cloudformation validate-template --template-body file://cloudformation-bucket.yaml

after_success:
  - echo "SUCCCESS"

after_failure:
  - echo "FAILURE"
