language: python

python:
  - "3.6"

env:
  - AWS_DEFAULT_REGION=us-west-2

install:
  - pip install --upgrade awscli
  - pip install yamllint

script:
  - yamllint cloudformation-bucket.yaml
  - aws cloudformation validate-template --template-body file://cloudformation-bucket.yml
