version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: 'us-west-2'
    CLOUDFORMATION_TEMPLATE = cloudformation-bucket.yml

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install yamllint
  build:
    commands:
      - yamllint ${CLOUDFORMATION_TEMPLATE}
      - aws cloudformation validate-template --template-body file://${CLOUDFORMATION_TEMPLATE}

artifacts:
  files: 
    - ${CLOUDFORMATION_TEMPLATE}
