version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: 'us-west-2'

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install yamllint
  build:
    commands:
      - yamllint cloudformation-bucket.yml
      - aws cloudformation validate-template --template-body file://cloudformation-bucket.yml
